/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yaz4j.jni;

public class CharStarByteArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CharStarByteArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CharStarByteArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      yaz4jlibJNI.delete_CharStarByteArray(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setData(String value) {
    yaz4jlibJNI.CharStarByteArray_data_set(swigCPtr, this, value);
  }

  public String getData() {
    return yaz4jlibJNI.CharStarByteArray_data_get(swigCPtr, this);
  }

  public void setLength(int value) {
    yaz4jlibJNI.CharStarByteArray_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return yaz4jlibJNI.CharStarByteArray_length_get(swigCPtr, this);
  }

  public CharStarByteArray() {
    this(yaz4jlibJNI.new_CharStarByteArray(), true);
  }

}
