/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yaz4j.jni;

public class SWIGTYPE_p_p_ZOOM_record_p {
  private long swigCPtr;

  protected SWIGTYPE_p_p_ZOOM_record_p(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_p_ZOOM_record_p() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_p_ZOOM_record_p obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

