/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yaz4j.jni;

class yaz4jlibJNI {
  public final static native long new_intp();
  public final static native long copy_intp(int jarg1);
  public final static native void delete_intp(long jarg1);
  public final static native void intp_assign(long jarg1, int jarg2);
  public final static native int intp_value(long jarg1);
  public final static native void CharStarByteArray_data_set(long jarg1, CharStarByteArray jarg1_, String jarg2);
  public final static native String CharStarByteArray_data_get(long jarg1, CharStarByteArray jarg1_);
  public final static native void CharStarByteArray_length_set(long jarg1, CharStarByteArray jarg1_, int jarg2);
  public final static native int CharStarByteArray_length_get(long jarg1, CharStarByteArray jarg1_);
  public final static native long new_CharStarByteArray();
  public final static native void delete_CharStarByteArray(long jarg1);
  public final static native byte[] ZOOM_record_get_bytes(long jarg1, String jarg2, long jarg3);
  public final static native long ZOOM_connection_new(String jarg1, int jarg2);
  public final static native long ZOOM_connection_create(long jarg1);
  public final static native void ZOOM_connection_connect(long jarg1, String jarg2, int jarg3);
  public final static native void ZOOM_connection_destroy(long jarg1);
  public final static native String ZOOM_connection_option_get(long jarg1, String jarg2);
  public final static native String ZOOM_connection_option_getl(long jarg1, String jarg2, long jarg3);
  public final static native void ZOOM_connection_option_set(long jarg1, String jarg2, String jarg3);
  public final static native void ZOOM_connection_option_setl(long jarg1, String jarg2, String jarg3, int jarg4);
  public final static native int ZOOM_connection_error(long jarg1, long jarg2, long jarg3);
  public final static native int ZOOM_connection_error_x(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int ZOOM_connection_errcode(long jarg1);
  public final static native String ZOOM_connection_errmsg(long jarg1);
  public final static native String ZOOM_connection_addinfo(long jarg1);
  public final static native String ZOOM_connection_diagset(long jarg1);
  public final static native String ZOOM_diag_str(int jarg1);
  public final static native int ZOOM_connection_last_event(long jarg1);
  public final static native long ZOOM_connection_search(long jarg1, long jarg2);
  public final static native long ZOOM_connection_search_pqf(long jarg1, String jarg2);
  public final static native void ZOOM_resultset_destroy(long jarg1);
  public final static native String ZOOM_resultset_option_get(long jarg1, String jarg2);
  public final static native void ZOOM_resultset_option_set(long jarg1, String jarg2, String jarg3);
  public final static native long ZOOM_resultset_size(long jarg1);
  public final static native void ZOOM_resultset_records(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long ZOOM_resultset_record(long jarg1, long jarg2);
  public final static native long ZOOM_resultset_record_immediate(long jarg1, long jarg2);
  public final static native void ZOOM_resultset_cache_reset(long jarg1);
  public final static native String ZOOM_record_get(long jarg1, String jarg2, long jarg3);
  public final static native void ZOOM_record_destroy(long jarg1);
  public final static native long ZOOM_record_clone(long jarg1);
  public final static native long ZOOM_query_create();
  public final static native void ZOOM_query_destroy(long jarg1);
  public final static native int ZOOM_query_cql(long jarg1, String jarg2);
  public final static native int ZOOM_query_cql2rpn(long jarg1, String jarg2, long jarg3);
  public final static native int ZOOM_query_ccl2rpn(long jarg1, String jarg2, String jarg3, long jarg4, long jarg5, long jarg6);
  public final static native int ZOOM_query_prefix(long jarg1, String jarg2);
  public final static native int ZOOM_query_sortby(long jarg1, String jarg2);
  public final static native long ZOOM_connection_scan(long jarg1, String jarg2);
  public final static native long ZOOM_connection_scan1(long jarg1, long jarg2);
  public final static native String ZOOM_scanset_term(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native String ZOOM_scanset_display_term(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native long ZOOM_scanset_size(long jarg1);
  public final static native void ZOOM_scanset_destroy(long jarg1);
  public final static native String ZOOM_scanset_option_get(long jarg1, String jarg2);
  public final static native void ZOOM_scanset_option_set(long jarg1, String jarg2, String jarg3);
  public final static native long ZOOM_connection_package(long jarg1, long jarg2);
  public final static native void ZOOM_package_destroy(long jarg1);
  public final static native void ZOOM_package_send(long jarg1, String jarg2);
  public final static native String ZOOM_package_option_get(long jarg1, String jarg2);
  public final static native void ZOOM_package_option_set(long jarg1, String jarg2, String jarg3);
  public final static native void ZOOM_resultset_sort(long jarg1, String jarg2, String jarg3);
  public final static native int ZOOM_resultset_sort1(long jarg1, String jarg2, String jarg3);
  public final static native long ZOOM_options_set_callback(long jarg1, long jarg2, long jarg3);
  public final static native long ZOOM_options_create();
  public final static native long ZOOM_options_create_with_parent(long jarg1);
  public final static native long ZOOM_options_create_with_parent2(long jarg1, long jarg2);
  public final static native String ZOOM_options_get(long jarg1, String jarg2);
  public final static native String ZOOM_options_getl(long jarg1, String jarg2, long jarg3);
  public final static native void ZOOM_options_set(long jarg1, String jarg2, String jarg3);
  public final static native void ZOOM_options_setl(long jarg1, String jarg2, String jarg3, int jarg4);
  public final static native void ZOOM_options_destroy(long jarg1);
  public final static native int ZOOM_options_get_bool(long jarg1, String jarg2, int jarg3);
  public final static native int ZOOM_options_get_int(long jarg1, String jarg2, int jarg3);
  public final static native void ZOOM_options_set_int(long jarg1, String jarg2, int jarg3);
  public final static native int ZOOM_event(int jarg1, long jarg2);
}
