/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.yaz4j.jni;

public interface yaz4jlibConstants {
  public final static int ZOOM_ERROR_NONE = 0;
  public final static int ZOOM_ERROR_CONNECT = 10000;
  public final static int ZOOM_ERROR_MEMORY = 10001;
  public final static int ZOOM_ERROR_ENCODE = 10002;
  public final static int ZOOM_ERROR_DECODE = 10003;
  public final static int ZOOM_ERROR_CONNECTION_LOST = 10004;
  public final static int ZOOM_ERROR_INIT = 10005;
  public final static int ZOOM_ERROR_INTERNAL = 10006;
  public final static int ZOOM_ERROR_TIMEOUT = 10007;
  public final static int ZOOM_ERROR_UNSUPPORTED_PROTOCOL = 10008;
  public final static int ZOOM_ERROR_UNSUPPORTED_QUERY = 10009;
  public final static int ZOOM_ERROR_INVALID_QUERY = 10010;
  public final static int ZOOM_ERROR_CQL_PARSE = 10011;
  public final static int ZOOM_ERROR_CQL_TRANSFORM = 10012;
  public final static int ZOOM_ERROR_CCL_CONFIG = 10013;
  public final static int ZOOM_ERROR_CCL_PARSE = 10014;
  public final static int ZOOM_EVENT_NONE = 0;
  public final static int ZOOM_EVENT_CONNECT = 1;
  public final static int ZOOM_EVENT_SEND_DATA = 2;
  public final static int ZOOM_EVENT_RECV_DATA = 3;
  public final static int ZOOM_EVENT_TIMEOUT = 4;
  public final static int ZOOM_EVENT_UNKNOWN = 5;
  public final static int ZOOM_EVENT_SEND_APDU = 6;
  public final static int ZOOM_EVENT_RECV_APDU = 7;
  public final static int ZOOM_EVENT_RECV_RECORD = 8;
  public final static int ZOOM_EVENT_RECV_SEARCH = 9;
  public final static int ZOOM_EVENT_END = 10;
}
