.\"     Title: yaz\-config
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 09/04/2006
.\"    Manual: 
.\"    Source: YAZ 2.1.28
.\"
.TH "YAZ\-CONFIG" "8" "09/04/2006" "YAZ 2.1.28" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
yaz\-config \- Script to get information about YAZ.
.SH "SYNOPSIS"
.HP 11
\fByaz\-config\fR [\fB\-\-prefix[=\fR\fB\fIDIR\fR\fR\fB]\fR] [\fB\-\-version\fR] [\fB\-\-libs\fR] [\fB\-\-lalibs\fR] [\fB\-\-cflags\fR] [\fB\-\-comp\fR] [libraries...]
.SH "DESCRIPTION"
.PP

\fByaz\-config\fR
is a script that returns information that your own software should use to build software that uses YAZ.
.PP
The following libraries are supported:
.TP 3n
threads
Use the threaded version of YAZ.
.SH "OPTIONS"
.TP 3n
\-\-prefix[=\fIDIR\fR]
Returns prefix of YAZ or assume a different one if DIR is specified.
.TP 3n
\-\-version
Returns version of YAZ.
.TP 3n
\-\-libs
Library specification be used when using YAZ.
.TP 3n
\-\-lalibs
Return library specification.
.TP 3n
\-\-cflags
Return C Compiler flags.
.TP 3n
\-\-comp
Returns full path to YAZ' ASN.1 compiler: yaz\-asncomp.
.SH "FILES"
.PP

\fI\fIprefix\fR\fR\fI/bin/yaz\-config\fR
.PP

\fI\fIprefix\fR\fR\fI/lib/libyaz*.a\fR
.PP

\fI\fIprefix\fR\fR\fI/include/yaz/*.h\fR
.SH "SEE ALSO"
.PP
yaz(7)
.PP
Section "How to make apps using YAZ on UNIX" in the YAZ manual.
