.\"     Title: yaz
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: 09/04/2006
.\"    Manual: 
.\"    Source: YAZ 2.1.28
.\"
.TH "YAZ" "7" "09/04/2006" "YAZ 2.1.28" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
yaz \- Z39.50 toolkit.
.SH "SYNOPSIS"
.HP 4
\fBYAZ\fR
.SH "DESCRIPTION"
.PP
YAZ is a C/C++ programmer's toolkit supporting the development of Z39.50v3 clients and servers. The YAZ toolkit offers several different levels of access to the ISO23950/Z39.50, SRU and ILL protocols. The level that you need to use depends on your requirements, and the role (server of client) that you want to implement.
.SH "COPYRIGHT"
.PP
Copyright (c) 1995\-2006, Index Data ApS.
.PP
Permission to use, copy, modify, distribute, and sell this software and its documentation, in whole or in part, for any purpose, is hereby granted, provided that:
.PP
1. This copyright and permission notice appear in all copies of the software and its documentation. Notices of copyright or attribution which appear at the beginning of any file must remain unchanged.
.PP
2. The names of Index Data or the individual authors may not be used to endorse or promote products derived from this software without specific prior written permission.
.PP
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED, OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. IN NO EVENT SHALL INDEX DATA BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.SH "SEE ALSO"
.PP

\fByaz\-client\fR(1),
\fByaz\-ztest\fR(8),
\fByaz\-config\fR(8),
\fBzoomsh\fR(1)
.PP
YAZ manual (
\fI/usr/local/share/doc/yaz\fR)
.PP

[1]\&\fIYAZ home page\fR.
.PP

[2]\&\fIZ39.50 Maintenance Agency Page\fR.
.SH "REFERENCES"
.TP 3
1.\ YAZ home page
\%http://www.indexdata.com/yaz/
.TP 3
2.\ Z39.50 Maintenance Agency Page
\%http://www.loc.gov/z3950/agency/
